spring:
  application:
    name: microservice-b
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    enabled: true
    sampler:
      percentage: 1
server:
  port: 8882
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/